import Link from 'next/link'
import { Activity, AlertTriangle, ArrowUpRight, Building2, CircleDollarSign, FileCheck2, Gauge, Landmark, Plus, ReceiptText, ShieldCheck, Users } from 'lucide-react'
import { logout } from '@/app/auth/actions'
import { createExpense } from './actions'
import { requirePlatformAdmin } from '@/lib/server/platform-admin'

type Money = Record<string, number>
type Subscription = { tenant_id:string; plan_code:string; provider:string; status:string; currency:string; unit_amount:number; current_period_end:string|null }
type Tenant = { id:string; name:string; status:string; created_at:string }
type Expense = { id:string; occurred_on:string; category:string; vendor:string; description:string|null; currency:string; amount:number; recurring:boolean }
const activeStatuses = new Set(['active','trialing'])
const roleLabels:Record<string,string>={owner:'Propietario',finance:'Finanzas',operations:'Operaciones'}
const money = (amount:number,currency:string) => new Intl.NumberFormat('es-CO',{style:'currency',currency,maximumFractionDigits:0}).format(amount/100)
const date = (value:string|null) => value ? new Intl.DateTimeFormat('es-CO',{dateStyle:'medium'}).format(new Date(value)) : '—'
const add = (target:Money,currency:string,amount:number) => { target[currency]=(target[currency]??0)+amount }

function Metric({label,value,detail,icon:Icon,tone='blue'}:{label:string;value:string;detail:string;icon:typeof Users;tone?:'blue'|'green'|'amber'|'violet'}) {
  const colors={blue:'bg-blue-500/15 text-blue-300',green:'bg-emerald-500/15 text-emerald-300',amber:'bg-amber-500/15 text-amber-300',violet:'bg-violet-500/15 text-violet-300'}
  return <article className="rounded-2xl border border-white/10 bg-[#121720] p-5"><div className={`mb-4 inline-flex rounded-xl p-2.5 ${colors[tone]}`}><Icon size={20}/></div><p className="text-sm text-slate-400">{label}</p><p className="mt-1 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></article>
}

export default async function AdminPage({searchParams}:{searchParams:Promise<{error?:string;message?:string}>}) {
  const [{admin,email,role},notice]=await Promise.all([requirePlatformAdmin(),searchParams])
  const currentTime=new Date()
  const monthStart=new Date(currentTime); monthStart.setDate(1); monthStart.setHours(0,0,0,0)
  const since24h=new Date(currentTime.getTime()-86400000).toISOString()
  const [tenantsQ,subsQ,expensesQ,documentsQ,jobsQ,alertsQ,membersQ]=await Promise.all([
    admin.from('tenants').select('id,name,status,created_at').order('created_at',{ascending:false}),
    admin.from('subscriptions').select('tenant_id,plan_code,provider,status,currency,unit_amount,current_period_end').order('created_at',{ascending:false}),
    admin.from('platform_expenses').select('id,occurred_on,category,vendor,description,currency,amount,recurring').order('occurred_on',{ascending:false}).limit(20),
    admin.from('documents').select('id,tenant_id,status,created_at'),
    admin.from('analysis_jobs').select('id,status,created_at').gte('created_at',since24h),
    admin.from('operational_alerts').select('id,severity,title,status,last_seen_at,occurrence_count').in('status',['open','acknowledged']).order('last_seen_at',{ascending:false}).limit(8),
    admin.from('tenant_members').select('user_id').eq('status','active'),
  ])
  const queries=[tenantsQ,subsQ,expensesQ,documentsQ,jobsQ,alertsQ,membersQ]
  if(queries.some(q=>q.error)) throw new Error('No fue posible cargar la analítica administrativa.')
  const tenants=(tenantsQ.data??[]) as Tenant[], subscriptions=(subsQ.data??[]) as Subscription[], expenses=(expensesQ.data??[]) as Expense[]
  const activeSubs=subscriptions.filter(s=>activeStatuses.has(s.status)); const mrr:Money={},monthExpenses:Money={}
  activeSubs.filter(s=>s.status==='active').forEach(s=>add(mrr,s.currency,s.unit_amount))
  expenses.filter(e=>new Date(`${e.occurred_on}T00:00:00`)>=monthStart).forEach(e=>add(monthExpenses,e.currency,e.amount))
  const financialCurrencies=[...new Set([...Object.keys(mrr),...Object.keys(monthExpenses)])]
  const latestSub=new Map<string,Subscription>()
  subscriptions.forEach(s=>{if(!latestSub.has(s.tenant_id))latestSub.set(s.tenant_id,s)})
  const docs=documentsQ.data??[], jobs=jobsQ.data??[], failedJobs=jobs.filter(j=>j.status==='failed').length
  const completedMonth=docs.filter(d=>d.status==='completed'&&new Date(d.created_at)>=monthStart).length
  const input='h-10 rounded-xl border border-white/10 bg-[#0d1118] px-3 text-sm text-white placeholder:text-slate-600'
  return <main className="min-h-screen bg-[#090c12] text-slate-100">
    <header className="sticky top-0 z-20 border-b border-white/10 bg-[#090c12]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1600px] items-center justify-between px-6 py-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-500 p-2"><ShieldCheck size={22}/></div><div><p className="font-bold">Control de KRONOVA</p><p className="text-xs text-slate-500">Administración privada · {roleLabels[role]??role}</p></div></div><div className="flex items-center gap-3 text-sm"><span className="hidden text-slate-400 md:inline">{email}</span><Link href="/dashboard" className="rounded-xl border border-white/10 px-4 py-2 hover:bg-white/5">Vista de cliente</Link><form action={logout}><button className="rounded-xl border border-white/10 px-4 py-2 hover:bg-white/5">Salir</button></form></div></div></header>
    <div className="mx-auto max-w-[1600px] space-y-7 px-6 py-8">
      <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-medium text-blue-400">CENTRO DE CONTROL</p><h1 className="mt-1 text-3xl font-semibold">Estado general de KRONOVA</h1><p className="mt-2 text-slate-400">Datos reales consolidados de todas las organizaciones.</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-4 py-2 text-sm text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Sistema conectado</div></section>
      {notice.error&&<p className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">{notice.error}</p>}{notice.message&&<p className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-200">{notice.message}</p>}
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Empresas registradas" value={String(tenants.length)} detail={`${activeSubs.length} suscripciones activas o en prueba`} icon={Building2}/><Metric label="Usuarios activos" value={String(membersQ.data?.length??0)} detail="Miembros activos en todas las empresas" icon={Users} tone="violet"/><Metric label="Documentos este mes" value={String(completedMonth)} detail={`${docs.length} documentos almacenados en total`} icon={FileCheck2} tone="green"/><Metric label="Alertas abiertas" value={String(alertsQ.data?.length??0)} detail={`${failedJobs} trabajos fallidos en las últimas 24 h`} icon={AlertTriangle} tone={(alertsQ.data?.length??0)>0?'amber':'green'}/></section>
      <section className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><article className="rounded-2xl border border-white/10 bg-[#121720] p-6"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><Landmark size={20} className="text-emerald-400"/>Resumen financiero mensual</h2><p className="mt-1 text-sm text-slate-500">Ingreso contratado menos gastos registrados; separado por moneda.</p></div></div>{financialCurrencies.length?<div className="mt-6 grid gap-3 md:grid-cols-3">{financialCurrencies.map(currency=>{const revenue=mrr[currency]??0,cost=monthExpenses[currency]??0;return <div key={currency} className="rounded-xl bg-black/20 p-4"><p className="text-xs font-medium text-slate-500">{currency}</p><p className="mt-3 text-xs text-slate-400">Ingreso mensual contratado</p><p className="text-xl font-semibold text-emerald-300">{money(revenue,currency)}</p><p className="mt-3 text-xs text-slate-400">Gastos del mes</p><p className="text-lg text-rose-300">− {money(cost,currency)}</p><div className="my-3 h-px bg-white/10"/><p className="text-xs text-slate-400">Resultado proyectado</p><p className={`text-xl font-semibold ${revenue-cost>=0?'text-blue-300':'text-rose-300'}`}>{money(revenue-cost,currency)}</p></div>})}</div>:<div className="mt-6 rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">Aún no hay suscripciones pagadas ni gastos registrados.</div>}<p className="mt-4 text-xs text-slate-600">El ingreso corresponde a suscripciones activas, no a conciliación bancaria. Mercado Pago se reflejará cuando su integración esté habilitada.</p></article>
      <article className="rounded-2xl border border-white/10 bg-[#121720] p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><Plus size={20} className="text-blue-400"/>Registrar gasto</h2><form action={createExpense} className="mt-5 grid gap-3"><div className="grid grid-cols-2 gap-3"><input name="occurredOn" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className={input}/><select name="category" className={input}><option value="ai">Inteligencia artificial</option><option value="infrastructure">Infraestructura</option><option value="marketing">Marketing</option><option value="software">Software</option><option value="accounting">Contabilidad</option><option value="legal">Legal</option><option value="payroll">Nómina</option><option value="taxes">Impuestos</option><option value="other">Otro</option></select></div><input name="vendor" required placeholder="Proveedor" className={input}/><input name="description" placeholder="Descripción opcional" className={input}/><div className="grid grid-cols-[1fr_90px] gap-3"><input name="amount" type="number" min="0.01" step="0.01" required placeholder="Valor" className={input}/><select name="currency" defaultValue="COP" className={input}><option>COP</option><option>USD</option></select></div><label className="flex items-center gap-2 text-sm text-slate-400"><input name="recurring" type="checkbox"/>Es un gasto recurrente</label><button className="h-10 rounded-xl bg-blue-500 font-medium text-slate-950 hover:bg-blue-400">Guardar gasto</button></form></article></section>
      <section className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><article className="overflow-hidden rounded-2xl border border-white/10 bg-[#121720]"><div className="flex items-center justify-between p-6"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><Building2 size={20} className="text-blue-400"/>Empresas y suscripciones</h2><p className="mt-1 text-sm text-slate-500">Últimas organizaciones registradas.</p></div><span className="text-xs text-slate-500">{tenants.length} total</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y border-white/10 bg-black/15 text-xs text-slate-500"><tr><th className="px-6 py-3">Empresa</th><th className="px-4 py-3">Plan</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Renovación</th></tr></thead><tbody>{tenants.slice(0,10).map(t=>{const s=latestSub.get(t.id);return <tr key={t.id} className="border-b border-white/5"><td className="px-6 py-4"><p className="font-medium">{t.name}</p><p className="text-xs text-slate-600">Alta {date(t.created_at)}</p></td><td className="px-4 py-4">{s?.plan_code??'Sin plan'}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs ${s&&activeStatuses.has(s.status)?'bg-emerald-500/10 text-emerald-300':'bg-slate-500/10 text-slate-400'}`}>{s?.status??t.status}</span></td><td className="px-4 py-4 text-slate-400">{date(s?.current_period_end??null)}</td></tr>})}</tbody></table></div></article>
      <article className="rounded-2xl border border-white/10 bg-[#121720] p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><Activity size={20} className="text-violet-400"/>Operación</h2><div className="mt-5 space-y-3"><div className="flex justify-between rounded-xl bg-black/20 p-4"><span className="flex items-center gap-2 text-slate-400"><Gauge size={17}/>Trabajos 24 h</span><strong>{jobs.length}</strong></div><div className="flex justify-between rounded-xl bg-black/20 p-4"><span className="flex items-center gap-2 text-slate-400"><AlertTriangle size={17}/>Fallidos 24 h</span><strong className={failedJobs?'text-rose-300':'text-emerald-300'}>{failedJobs}</strong></div><div className="flex justify-between rounded-xl bg-black/20 p-4"><span className="flex items-center gap-2 text-slate-400"><ReceiptText size={17}/>Gastos registrados</span><strong>{expenses.length}</strong></div></div>{(alertsQ.data??[]).length>0&&<div className="mt-5 space-y-2"><p className="text-xs font-medium uppercase tracking-wider text-slate-500">Alertas recientes</p>{(alertsQ.data??[]).map(a=><div key={a.id} className="rounded-xl border border-amber-500/10 bg-amber-500/5 p-3"><p className="text-sm text-amber-200">{a.title}</p><p className="mt-1 text-xs text-slate-600">{a.occurrence_count} ocurrencias · {date(a.last_seen_at)}</p></div>)}</div>}</article></section>
      <section className="rounded-2xl border border-white/10 bg-[#121720] p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><CircleDollarSign size={20} className="text-emerald-400"/>Últimos gastos</h2>{expenses.length?<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="pb-3">Fecha</th><th className="pb-3">Proveedor</th><th className="pb-3">Categoría</th><th className="pb-3">Tipo</th><th className="pb-3 text-right">Valor</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id} className="border-t border-white/5"><td className="py-3 text-slate-400">{date(e.occurred_on)}</td><td className="py-3"><p>{e.vendor}</p>{e.description&&<p className="text-xs text-slate-600">{e.description}</p>}</td><td className="py-3 text-slate-400">{e.category}</td><td className="py-3 text-slate-400">{e.recurring?'Recurrente':'Único'}</td><td className="py-3 text-right font-medium">{money(e.amount,e.currency)}</td></tr>)}</tbody></table></div>:<p className="mt-5 text-sm text-slate-500">No hay gastos registrados.</p>}</section>
      <footer className="flex items-center justify-between border-t border-white/10 py-5 text-xs text-slate-600"><span>KRONOVA Control · datos en tiempo real</span><span className="flex items-center gap-1">Acceso protegido <ArrowUpRight size={12}/></span></footer>
    </div></main>
}
